spring:
  datasource:
    url: jdbc:mysql://rm-bp1dfy7v5qt0m3gkm1o.mysql.rds.aliyuncs.com:3306/mall_wms
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zks123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-ware
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 11000