server:
  port: 25000
spring:
  application:
    name: mall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 118.31.38.90
  session:
    store-type: redis
  task:
    execution:
      pool:
        core-size: 10
        max-size: 50
  rabbitmq:
    virtual-host: /
    host: 118.31.38.90

#  task:
#    scheduling:
#      pool:
#        size: 10