spring:
  application:
    name: mall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  redis:
    host: 118.31.38.90
    port: 6379
  session:
    store-type: redis
server:
  port: 20000
  servlet:
    session:
      timeout: 30m